import { expect, test } from '@playwright/test'

test('deep links and reloads the brand-scoped integration surface', async ({ page }) => {
  await page.goto('./integrations?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Integrations' })).toBeVisible()
  await expect(page.getByText('Choose how Brand OS connects')).toBeVisible()
  await expect(page.getByText('secrets are write-only')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Live readiness')).toBeVisible()
  await expect(page.getByRole('button', { name: /^publish$/i })).toHaveCount(0)
})

test('configures and heartbeats an agent in a disposable development database', async ({ page }) => {
  await page.goto('./agents?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Agents & live readiness' })).toBeVisible()
  await page.getByLabel('Agent ID for Demo Brand').fill('e2e-browser')
  await page.getByRole('button', { name: 'Configure & enable' }).click()
  await expect(page.getByText('e2e-browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Heartbeat' }).click()
  await expect(page.getByText('ready to claim')).toBeVisible()
})

test('keeps governed execution usable at a mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./execution?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Execution' })).toBeVisible()
  await expect(page.getByText('Assisted execution only.')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('link', { name: 'Execution' })).toBeVisible()
  await expect(page.getByRole('button', { name: /^publish$/i })).toHaveCount(0)
})

test('fails closed on network errors and an unknown brand scope', async ({ page }) => {
  await page.route('**/api/brands/demo-brand/readiness', (route) => route.abort('failed'))
  await page.goto('./agents?brand=demo-brand')
  await expect(page.getByText('Failed to fetch')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry' })).toBeVisible()

  await page.unroute('**/api/brands/demo-brand/readiness')
  await page.goto('./integrations?brand=not-a-real-brand')
  await expect(page.getByText('Select one brand to review or change its connections.')).toBeVisible()
  await expect(page.getByRole('button', { name: /^publish$/i })).toHaveCount(0)
})

test('creates a governed newsletter revision with a server-derived operator', async ({ page }) => {
  const created = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/newsletter-issues', {
    data: { content: { working_title: 'E2E draft issue', subject: 'Draft subject', preview_text: 'Draft preview' } },
  })
  expect(created.ok()).toBeTruthy()
  const issue = await created.json()
  await page.goto(`./content/newsletter/${issue.id}?brand=demo-brand`)
  await page.getByRole('button', { name: 'Create revised material' }).click()
  await page.getByLabel('Title').fill('E2E corrected issue')
  await page.getByLabel('Why this changed').fill('Correct the source-backed working title')
  await page.getByRole('button', { name: 'Create revision' }).click()
  await expect(page.getByText('Revision 2')).toBeVisible()
  const refreshed = await page.request.get(`http://127.0.0.1:8011/api/newsletter-issues/${issue.id}`)
  const revised = await refreshed.json()
  expect(revised.current_revision).toBe(2)
  expect(revised.content.created_by).toBe('preview-operator')
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('proposes an inactive Demo Brand instruction version without changing generation input', async ({ page }) => {
  await page.goto('./guidelines?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Guidelines' })).toBeVisible()
  const activeInstructions = page.getByLabel('Active instructions')
  await expect(activeInstructions).toContainText('Write in the brand voice')
  await expect(page.getByText('active v1', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Create version' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Exact generation instructions').fill('Write in the brand voice. Preserve the reviewed Demo Brand decision-support structure.')
  await dialog.getByLabel('Change reason').fill('Browser proof of a proposed instruction version.')
  await dialog.getByRole('button', { name: 'Create inactive version' }).click()
  await expect(page.getByText('Version 2')).toBeVisible()
  await expect(activeInstructions).toContainText('Write in the brand voice, in direct first person')
  await expect(page.getByText('active v1', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /^(send|publish|generate)$/i })).toHaveCount(0)
})

test('runs the learning lifecycle through explicit human decisions without publishing', async ({ page }) => {
  const beforePosts = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/context')
  const beforePostCount = ((await beforePosts.json()).campaigns ?? []).length
  await page.goto('./learnings?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Learnings & experiments' })).toBeVisible()
  await page.getByRole('button', { name: 'Propose learning' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Hypothesis').fill('E2E verified-number hypothesis')
  await dialog.getByLabel('Proposed bounded change').fill('Test a verified numeric hook when cited by the source')
  await dialog.getByLabel('Supporting evidence').fill('Aggregate observations from two campaigns')
  await dialog.getByRole('button', { name: 'Propose only' }).click()
  await expect(page.getByText('E2E verified-number hypothesis').first()).toBeVisible()
  await page.getByRole('button', { name: 'Start test' }).click()
  await expect(page.getByRole('button', { name: 'Accept evidence' })).toBeVisible()
  page.on('dialog', (prompt) => prompt.accept())
  await page.getByRole('button', { name: 'Accept evidence' }).click()
  await expect(page.getByText('accepted', { exact: true }).first()).toBeVisible()
  await expect(page.getByText(/preview-operator ·/).last()).toBeVisible()
  const after = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/context')
  expect(((await after.json()).campaigns ?? []).length).toBe(beforePostCount)
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('drafts and submits engagement for approval without direct execution', async ({ page }) => {
  await page.goto('./engagement?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Engagement' })).toBeVisible()
  await expect(page.getByText('E2E: should I change plans now?').first()).toBeVisible()
  await page.getByRole('button', { name: 'Draft governed action' }).click()
  await page.getByLabel('Reply draft').fill('Confirm the pricing page and plan limits before switching.')
  await page.getByRole('button', { name: 'Create draft only' }).click()
  await expect(page.getByRole('button', { name: 'Submit for approval' })).toBeVisible()
  page.on('dialog', (prompt) => prompt.accept())
  await page.getByRole('button', { name: 'Submit for approval' }).click()
  await expect(page.getByRole('link', { name: 'Review exact draft' })).toBeVisible()
  const history = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/engagement')
  const saved = (await history.json()).find((item: { external_post_id: string }) => item.external_post_id === '9910000001')
  expect(saved.state).toBe('awaiting_approval')
  const audit = await page.request.get(`http://127.0.0.1:8011/api/brands/demo-brand/engagement/${saved.id}/history`)
  const actions = await audit.json()
  expect(actions.filter((item: { action: string }) => ['action_drafted', 'awaiting_approval'].includes(item.action)).every((item: { actor: string }) => item.actor === 'preview-operator')).toBeTruthy()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule|like|follow)$/i })).toHaveCount(0)
})

for (const viewport of [{ name: 'desktop', width: 1440, height: 1000 }, { name: 'mobile', width: 390, height: 844 }]) {
  test(`previews draft structure honestly and saves only inert drafts on ${viewport.name}`, async ({ page }) => {
    await page.setViewportSize(viewport)
    const sourceResponse = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/sources', {
      data: { title: `E2E governed source ${viewport.name}`, source_type: 'manual', body_summary: 'Official terms end Friday.', url: 'https://issuer.test/e2e-terms', lifecycle_state: 'published' },
    })
    expect(sourceResponse.ok()).toBeTruthy()
    const source = await sourceResponse.json()
    await page.goto('./content?brand=demo-brand')
    await page.getByRole('button', { name: 'Create draft structure' }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByText(/No AI writing happens here/)).toBeVisible()
    await expect(dialog.getByText(/Writing instructions do not rewrite the source text/)).toBeVisible()
    await expect(dialog.getByText(`E2E governed source ${viewport.name}`, { exact: true })).toBeVisible()
    const beforePath = test.info().outputPath(`draft-structure-${viewport.name}.png`)
    await page.screenshot({ path: beforePath })
    await test.info().attach('draft structure input', { path: beforePath, contentType: 'image/png' })
    await dialog.getByLabel('Content goal').fill('Build a decision-support package from the selected official terms.')
    await dialog.getByText(`E2E governed source ${viewport.name}`, { exact: true }).click()
    await dialog.getByRole('button', { name: 'Preview draft structure' }).click()
    await expect(dialog.getByText('Exact active guideline binding')).toBeVisible()
    await expect(dialog.getByText(/No AI writing happens here/)).toBeVisible()
    await expect(dialog.getByText('X source-text draft')).toBeVisible()
    await expect(dialog.getByText(`E2E governed source ${viewport.name}: Official terms end Friday.`, { exact: true })).toBeVisible()
    const previewPath = test.info().outputPath(`draft-preview-${viewport.name}.png`)
    await page.screenshot({ path: previewPath })
    await test.info().attach('draft structure preview', { path: previewPath, contentType: 'image/png' })
    await expect(dialog.getByText(/^sha256:/)).toBeVisible()
    await expect(dialog.getByRole('button', { name: 'Save inert drafts' })).toBeDisabled()
    await dialog.getByLabel('Confirm inert drafts').check()
    await dialog.getByRole('button', { name: 'Save inert drafts' }).click()
    await expect(dialog.getByText(/Saved as inert drafts by preview-operator/)).toBeVisible()
    const context = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/context')
    const matching = (await context.json()).campaigns.find((item: { source_id: string; status: string }) => item.source_id === source.id)
    expect(matching.status).toBe('draft')
    const graph = await page.request.get(`http://127.0.0.1:8011/api/campaigns/${matching.id}/graph`)
    const graphBody = await graph.json()
    expect(graphBody.memberships.map((item: { asset_type: string; role: string }) => [item.asset_type, item.role])).toEqual([
      ['newsletter_issue', 'anchor'], ['post', 'touchpoint'],
    ])
    expect(graphBody.relationships).toHaveLength(1)
    await expect(dialog.getByRole('button', { name: /^(approve|send|publish|schedule)$/i })).toHaveCount(0)
  })
}

test('triages an agent-reported product failure through the audited feedback lifecycle', async ({ page }) => {
  const reported = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/product-feedback', {
    data: {
      reporter: 'demo-brand-agent', summary: 'E2E assisted handoff recovery failed',
      details: 'The execution agent could not find a safe recovery step.', component: 'execution', severity: 'high',
    },
  })
  expect(reported.ok()).toBeTruthy()
  const item = await reported.json()
  await page.goto(`./feedback/${item.id}?brand=demo-brand`)
  await expect(page.getByRole('heading', { name: 'Product feedback' })).toBeVisible()
  await expect(page.getByRole('button', { name: /E2E assisted handoff recovery failed/ })).toContainText('reported by demo-brand-agent')
  await page.getByLabel('Comment').fill('Operator reproduced this in the disposable browser run.')
  await page.getByRole('button', { name: 'Comment' }).click()
  await page.getByRole('button', { name: 'Start work' }).click()
  await page.getByLabel('Assignee').fill('builder')
  await page.getByRole('button', { name: 'Start work' }).last().click()
  await expect(page.getByRole('button', { name: 'Resolve with evidence' })).toBeVisible()
  await page.getByRole('button', { name: 'Resolve with evidence' }).click()
  await page.getByLabel('Resolution evidence').fill('Focused browser regression passes.')
  await page.getByRole('button', { name: 'Resolve', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Verify outcome' })).toBeVisible()
  await page.getByRole('button', { name: 'Verify outcome' }).click()
  await page.getByLabel('Verification evidence').fill('Verified in the disposable browser session.')
  await page.getByRole('button', { name: 'Verify', exact: true }).click()
  await page.getByRole('button', { name: 'Reopen' }).click()
  await page.getByLabel('Reason').fill('E2E confirms reopen remains available.')
  await page.getByRole('button', { name: 'Reopen' }).last().click()
  await expect(page.getByRole('button', { name: 'Start work' })).toBeVisible()

  const history = await page.request.get(`http://127.0.0.1:8011/api/brands/demo-brand/product-feedback/${item.id}/history`)
  const events = await history.json()
  expect(events[0].actor).toBe('demo-brand-agent')
  expect(events.slice(1).every((event: { actor: string }) => event.actor === 'preview-operator')).toBeTruthy()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('authors and promotes canonical content while failing closed before provider work', async ({ page }) => {
  const campaignResponse = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/campaigns', {
    data: { name: 'E2E canonical authoring', objective: 'Prove draft-only content authoring' },
  })
  const campaign = await campaignResponse.json()
  const candidateResponse = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/editorial-candidates', {
    data: { title: 'E2E campaign candidate', summary: 'Candidate-grounded decision support', dimensions: { relevance: 1, confidence: 1 }, recommended_treatment: 'newsletter_and_social' },
  })
  expect(candidateResponse.ok()).toBeTruthy()
  const candidate = await candidateResponse.json()

  await page.goto('./content?brand=demo-brand')
  await page.getByRole('button', { name: 'New campaign post' }).click()
  await page.getByLabel('Campaign').selectOption(campaign.id)
  await page.getByLabel('Post text').fill('E2E canonical campaign draft')
  await page.getByRole('button', { name: 'Save draft only' }).click()
  await page.getByRole('button', { name: /Campaign posts/ }).click()
  const postRow = page.getByRole('row').filter({ hasText: 'E2E canonical campaign draft' })
  await expect(postRow).toContainText('r1')
  await postRow.getByRole('button', { name: 'Edit' }).click()
  await page.getByLabel('Post text').fill('E2E canonical campaign revision')
  await page.getByRole('button', { name: 'Save draft only' }).click()
  const revisedRow = page.getByRole('row').filter({ hasText: 'E2E canonical campaign revision' })
  await expect(revisedRow).toContainText('r2')
  await revisedRow.getByRole('button', { name: 'Create review draft' }).click()

  await page.getByRole('button', { name: /Social drafts/ }).click()
  const dispatchRow = page.getByRole('row').filter({ hasText: 'E2E canonical campaign revision' })
  await expect(dispatchRow).toContainText('draft')
  await dispatchRow.getByRole('button', { name: 'Validation & history' }).click()
  await expect(page.getByText('Exact material is valid')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('preview-operator created')
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: /Campaign posts/ }).click()
  await revisedRow.getByRole('button', { name: 'Edit' }).click()
  await page.getByLabel('Post text').fill('Unsafe divergent edit')
  await page.getByRole('button', { name: 'Save draft only' }).click()
  await expect(page.getByText(/already has an exact dispatch copy/)).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()

  await page.getByRole('button', { name: /Ideas/ }).click()
  const candidateRow = page.getByRole('row').filter({ hasText: candidate.title })
  await candidateRow.getByRole('button', { name: 'Draft campaign post' }).click()
  await page.getByLabel('X post text').fill('E2E candidate-grounded draft')
  await page.getByRole('button', { name: 'Create draft material' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const candidateHistory = await page.request.get(`http://127.0.0.1:8011/api/editorial-candidates/${candidate.id}/history`)
  expect(candidateHistory.ok()).toBeTruthy()
  expect((await candidateHistory.json()).at(-1)).toMatchObject({ action: 'promoted_to_campaign_post', actor: 'preview-operator' })
  const tasks = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/execution-tasks')
  expect((await tasks.json()).filter((task: { source_id: string }) => task.source_id === campaign.id)).toHaveLength(0)
  await expect(page.getByRole('button', { name: /^(approve|send|publish|schedule)$/i })).toHaveCount(0)
})

test('adds a canonical source from a mobile deep link without provider action', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./sources?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Sources' })).toBeVisible()
  await page.getByRole('button', { name: 'Add canonical input' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Title').fill('E2E canonical issuer terms')
  await dialog.getByLabel('Summary or source note').fill('Public issuer terms queued for editorial review.')
  await dialog.getByLabel('Canonical public URL (optional)').fill('https://example.test/e2e-terms')
  await dialog.getByRole('button', { name: 'Save input' }).click()
  await expect(page.getByText('E2E canonical issuer terms')).toBeVisible()
  const context = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/context')
  expect((await context.json()).sources.some((item: { title: string }) => item.title === 'E2E canonical issuer terms')).toBeTruthy()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('records an exactly attributed aggregate outcome without a provider write', async ({ page }) => {
  const created = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/sources', {
    data: { title: 'E2E performance source', source_type: 'manual', body_summary: 'Attribution fixture', lifecycle_state: 'draft' },
  })
  expect(created.ok()).toBeTruthy()
  const source = await created.json()
  await page.goto('./performance?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Performance' })).toBeVisible()
  await page.getByRole('button', { name: 'Record aggregate outcome' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Campaign item or source').selectOption(`source:${source.id}`)
  await dialog.getByLabel('Clicks').fill('9')
  await dialog.getByLabel('Evidence note').fill('E2E aggregate provider observation')
  await dialog.getByRole('button', { name: 'Record evidence' }).click()
  await expect(page.getByText('E2E aggregate provider observation')).toBeVisible()
  const records = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/performance')
  const saved = (await records.json()).find((item: { notes: string }) => item.notes === 'E2E aggregate provider observation')
  expect(saved.source_id).toBe(source.id)
  expect(saved.post_id).toBeNull()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('audits a deep-linked brand setting edit and runs only a bounded brand tick', async ({ page }) => {
  await page.goto('./settings?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  const mission = page.getByLabel('Mission')
  const currentMission = await mission.inputValue()
  await mission.fill(`${currentMission} E2E reviewed.`)
  await page.getByLabel('Reason for this change').fill('E2E governed settings proof')
  await page.getByRole('button', { name: 'Save governed settings' }).click()
  await expect(page.getByText('E2E governed settings proof')).toBeVisible()
  await page.getByLabel('Decision limit').fill('1')
  await page.getByRole('button', { name: 'Run bounded tick' }).click()
  await expect(page.getByText('Brand-only orchestration tick completed.')).toBeVisible()
  await expect(page.getByText(/A tick does not call a provider/)).toBeVisible()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('creates a draft-only campaign from a mobile deep link', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./campaigns?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Campaigns' })).toBeVisible()
  await page.getByRole('button', { name: 'New campaign' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Campaign name').fill('E2E draft-only campaign')
  await dialog.getByLabel('Objective').fill('Prove campaign graph creation without provider execution')
  await dialog.getByRole('button', { name: 'Create draft' }).click()
  await expect(page.getByText('E2E draft-only campaign').first()).toBeVisible()
  const response = await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/campaign-graphs')
  const campaign = (await response.json()).find((item: { name: string }) => item.name === 'E2E draft-only campaign')
  expect(campaign.status).toBe('draft')
  expect(campaign.memberships).toHaveLength(0)
  await expect(page.getByText('draft graph only · no publishing')).toBeVisible()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('configures, previews, commits, and exactly undoes planning metadata only', async ({ page }) => {
  const campaignResponse = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/campaigns', {
    data: { name: 'E2E planner campaign', objective: 'Prove planning-only reflow' },
  })
  expect(campaignResponse.ok()).toBeTruthy()
  const campaign = await campaignResponse.json()
  const postResponse = await page.request.post(`http://127.0.0.1:8011/api/campaigns/${campaign.id}/posts`, {
    data: { channel: 'x', body: 'E2E planner-only draft' },
  })
  expect(postResponse.ok()).toBeTruthy()
  const post = await postResponse.json()
  const canonicalBefore = await (await page.request.get(`http://127.0.0.1:8011/api/campaigns/${campaign.id}/posts`)).json()
  const providerBefore = await (await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/dispatch-items')).json()

  await page.goto('./planner?brand=demo-brand')
  await expect(page.getByRole('heading', { name: 'Planner' })).toBeVisible()
  await expect(page.getByText('E2E planner-only draft').first()).toBeVisible()
  await page.getByLabel('Timezone for Demo Brand').fill('America/New_York')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByText('Publishing-plan settings saved. Provider schedules were not changed.')).toBeVisible()
  await page.getByRole('button', { name: 'Preview reflow' }).click()
  await expect(page.getByText('Proposed changes')).toBeVisible()
  page.on('dialog', (prompt) => prompt.accept())
  await page.getByRole('button', { name: 'Commit planning changes' }).click()
  await expect(page.getByRole('button', { name: 'Undo exact reflow' })).toBeVisible()
  const committedPlan = await (await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/publishing-plan')).json()
  const committedItem = committedPlan.initiatives.flatMap((item: { items: unknown[] }) => item.items).find((item: { item_id: string }) => item.item_id === post.id)
  expect(committedItem.planned_for).not.toBeNull()
  await page.getByRole('button', { name: 'Undo exact reflow' }).click()
  await expect(page.getByText('Exact reflow undo completed.')).toBeVisible()
  const restoredPlan = await (await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/publishing-plan')).json()
  const restoredItem = restoredPlan.initiatives.flatMap((item: { items: unknown[] }) => item.items).find((item: { item_id: string }) => item.item_id === post.id)
  expect(restoredItem.planned_for).toBeNull()
  expect(await (await page.request.get(`http://127.0.0.1:8011/api/campaigns/${campaign.id}/posts`)).json()).toEqual(canonicalBefore)
  expect(await (await page.request.get('http://127.0.0.1:8011/api/brands/demo-brand/dispatch-items')).json()).toEqual(providerBefore)
  await expect(page.getByText(/never approve, schedule with a provider, or publish/i)).toBeVisible()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('keeps deep-linked Feedback single-column on mobile and recovers from a failed read', async ({ page }) => {
  const reported = await page.request.post('http://127.0.0.1:8011/api/brands/demo-brand/product-feedback', {
    data: { reporter: 'mobile-e2e-agent', summary: 'E2E mobile feedback recovery', details: 'Responsive detail proof.', component: 'dashboard', severity: 'medium' },
  })
  expect(reported.ok()).toBeTruthy()
  const item = await reported.json()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`./feedback/${item.id}?brand=demo-brand`)
  await expect(page.getByText('E2E mobile feedback recovery').first()).toBeVisible()
  const cards = page.locator('.feedback-layout > .card')
  const listBox = await cards.nth(0).boundingBox(), detailBox = await cards.nth(1).boundingBox()
  expect(listBox).not.toBeNull(); expect(detailBox).not.toBeNull()
  expect(detailBox!.y).toBeGreaterThan(listBox!.y)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBeTruthy()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)

  await page.route('**/api/brands/demo-brand/product-feedback', (route) => route.abort('failed'))
  await page.reload()
  await expect(page.getByText('Failed to fetch')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry' })).toBeVisible()
  await page.unroute('**/api/brands/demo-brand/product-feedback')
  await page.getByRole('button', { name: 'Retry' }).click()
  await expect(page.getByText('E2E mobile feedback recovery').first()).toBeVisible()
})

test('fails closed and recovers before exposing Settings mutations', async ({ page }) => {
  await page.route('**/api/brands/demo-brand/settings', (route) => route.abort('failed'))
  await page.goto('./settings?brand=demo-brand')
  await expect(page.getByText('Failed to fetch')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save governed settings' })).toHaveCount(0)
  await page.unroute('**/api/brands/demo-brand/settings')
  await page.getByRole('button', { name: 'Retry' }).click()
  await expect(page.getByRole('button', { name: 'Save governed settings' })).toBeVisible()
  await expect(page.getByRole('button', { name: /^(send|publish|schedule)$/i })).toHaveCount(0)
})

test('keeps the Content page inside the 390px viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./content?brand=demo-brand')
  await expect(page.getByRole('button', { name: /new newsletter/i })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBeTruthy()
})
