import { useState } from 'react'
import { campaignGraphs, brands as brandsApi } from '../api/endpoints'
import type { CampaignGraph, CampaignMembership, CampaignTemplate, Source } from '../api/types'
import { describe, useLoad } from '../api/useLoad'
import { ChannelIcon, Icon } from '../components/icons'
import { Shell } from '../components/Shell'
import { Card, CardHeader, Chip, Empty, ErrorState, Loading, Modal, StatusChip } from '../components/ui'
import { money, relTime, shortDateTime, titleCase } from '../lib/format'
import { useBrands } from '../state/BrandContext'
import { useToast } from '../state/Toast'

type Dialog = 'create' | 'template' | 'attach' | 'relationship' | 'flight' | 'metric' | null

async function loadCampaigns(slug: string) {
  const [graphs, templates, context, packages] = await Promise.all([
    campaignGraphs.list(slug), campaignGraphs.templates(), brandsApi.context(slug), campaignGraphs.packages(slug),
  ])
  return { graphs, templates, sources: context.sources, packages }
}

export default function Campaigns() {
  const { selected, active } = useBrands()
  const brand = selected ? active[0] : undefined
  const load = useLoad(() => brand ? loadCampaigns(brand.slug) : Promise.resolve(null), [brand?.slug])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [dialog, setDialog] = useState<Dialog>(null)
  const [metricMember, setMetricMember] = useState<CampaignMembership | null>(null)
  const effectiveSelectedId = selectedId && load.data?.graphs.some((item) => item.id === selectedId)
    ? selectedId : load.data?.graphs[0]?.id ?? null
  const detail = useLoad(async () => {
    if (!effectiveSelectedId) return null
    const [graph, measurement, audit] = await Promise.all([campaignGraphs.get(effectiveSelectedId), campaignGraphs.measurement(effectiveSelectedId), campaignGraphs.audit(effectiveSelectedId)])
    return { graph, measurement, audit }
  }, [effectiveSelectedId])
  const { notify } = useToast()
  const graph = detail.data?.graph ?? load.data?.graphs.find((item) => item.id === effectiveSelectedId) ?? load.data?.graphs[0]
  const activeMembers = graph?.memberships.filter((item) => Boolean(item.active)) ?? []
  const refresh = () => { load.reload(); detail.reload() }
  const act = async (label: string, fn: () => Promise<unknown>) => {
    try { await fn(); notify(label); refresh(); setDialog(null); setMetricMember(null) }
    catch (error) { notify(describe(error), 'bad') }
  }

  if (!selected) return <Shell title="Campaigns"><Card><Empty>Select one brand to manage its campaign graph.</Empty></Card></Shell>
  return <Shell title="Campaigns" crumb={brand?.name} right={<Chip kind="agent" icon="lock">draft graph only · no publishing</Chip>}>
    {load.error && <ErrorState message={load.error} retry={load.reload} />}
    {load.loading && !load.data && <Loading label="Loading campaign graphs…" />}
    {load.data && <>
      <div className="row" style={{ justifyContent: 'space-between' }}><div className="meta">Model the anchor, touchpoints, reader path, flight, and evidence before execution.</div><div className="row"><button className="btn" onClick={() => setDialog('template')}><Icon name="spark" size={14} />Use template</button><button className="btn primary" onClick={() => setDialog('create')}><Icon name="plus" size={14} />New campaign</button></div></div>
      <div className="campaign-layout">
        <Card className="campaign-list"><CardHeader title="Campaigns" sub={`${load.data.graphs.length}`} />{!load.data.graphs.length ? <Empty>No campaigns yet.</Empty> : load.data.graphs.map((item) => <button key={item.id} className={`list-item ${(graph?.id === item.id) ? 'on' : ''}`} onClick={() => setSelectedId(item.id)}><div className="row" style={{ justifyContent: 'space-between' }}><b>{item.name}</b><StatusChip status={item.status} /></div><div className="meta">{item.objective}</div><div className="meta">{item.memberships.filter((m) => Boolean(m.active)).length} active assets · {item.flights.length} flights</div></button>)}</Card>
        <div className="stack" style={{ gap: 12 }}>
          {!graph ? <Card><Empty>Create a campaign or instantiate a governed template to begin.</Empty></Card> : <>
            <Card><CardHeader icon="flag" title={graph.name} sub={graph.objective} right={<Chip kind={graph.primary_anchor ? 'ok' : 'human'}>{graph.primary_anchor ? 'anchor set' : 'needs anchor'}</Chip>} />
              <div className="card-b"><div className="campaign-flow">{activeMembers.map((member, index) => <div key={member.id} className="campaign-node"><div className="row"><ChannelIcon channel={member.channel} /><b>{titleCase(member.asset_type)}</b><Chip kind={member.role === 'anchor' ? 'human' : 'neutral'}>{member.role}</Chip></div><div className="mono">{member.asset_id}</div><div className="meta">{member.phase} · {member.flight_name}</div><div className="row campaign-node-actions"><button className="btn sm" onClick={() => { setMetricMember(member); setDialog('metric') }}>Record metric</button>{member.role !== 'anchor' && <button className="btn sm" onClick={() => act('Campaign anchor changed.', () => campaignGraphs.anchor(member.id, 'Operator selected this asset as the primary campaign anchor.'))}>Make anchor</button>}<button className="btn sm danger" onClick={() => window.confirm('Detach this asset from the campaign? Historical audit remains available.') && void act('Touchpoint detached.', () => campaignGraphs.detach(member.id, 'Operator removed this asset from the active campaign graph.'))}>Detach</button>{index > 0 && <button aria-label={`Move ${member.asset_id} up`} className="btn sm" onClick={() => void reorder(graph, activeMembers, index, index - 1, act)}>↑</button>}{index < activeMembers.length - 1 && <button aria-label={`Move ${member.asset_id} down`} className="btn sm" onClick={() => void reorder(graph, activeMembers, index, index + 1, act)}>↓</button>}</div></div>)}</div>{!activeMembers.length && <Empty>No active assets. Attach an anchor or touchpoint.</Empty>}</div>
              <div className="card-b campaign-toolbar"><button className="btn sm" onClick={() => setDialog('attach')}><Icon name="plus" size={13} />Attach asset</button><button className="btn sm" disabled={activeMembers.length < 2} onClick={() => setDialog('relationship')}>Add relationship</button><button className="btn sm" onClick={() => setDialog('flight')}><Icon name="calendar" size={13} />Add flight</button></div>
            </Card>
            <div className="grid campaigns-two-col"><Card><CardHeader title="Relationships" />{graph.relationships.length ? graph.relationships.map((rel) => <div key={rel.id} className="card-b campaign-row"><b>{rel.relationship_type}</b><div className="mono">{rel.from_membership_id.slice(0, 8)} → {rel.to_membership_id.slice(0, 8)}</div>{rel.notes && <div className="meta">{rel.notes}</div>}</div>) : <Empty>No declared reader paths.</Empty>}</Card><Card><CardHeader title="Flights" />{graph.flights.length ? graph.flights.map((flight) => <div key={flight.id} className="card-b campaign-row"><b>{flight.name}</b><div className="meta">{shortDateTime(flight.starts_at)} → {shortDateTime(flight.ends_at)}</div></div>) : <Empty>No bounded flights.</Empty>}</Card></div>
            <Measurement graph={graph} measurement={detail.data?.measurement} onMetric={(member) => { setMetricMember(member); setDialog('metric') }} />
            <TrackedDestination packages={load.data.packages.filter((item) => item.campaign_id === graph.id)} act={act} />
            <Card><CardHeader icon="history" title="Graph audit" sub="server-attributed mutations" />{detail.loading && <Loading />}{detail.data?.audit.length ? [...detail.data.audit].reverse().map((item, index) => <div className="feed-item" key={`${item.at}:${index}`}><div className="feed-ico human"><Icon name="history" size={14} /></div><div style={{ flex: 1 }}><b>{item.actor}</b> <span className="muted">{titleCase(item.action)} — {item.reason}</span></div><div className="meta">{relTime(item.at)}</div></div>) : <Empty>No graph audit entries loaded.</Empty>}</Card>
          </>}
        </div>
      </div>
      {dialog === 'create' && <CreateModal sources={load.data.sources} close={() => setDialog(null)} submit={(name, objective, source) => act('Draft campaign created.', async () => { const made = await campaignGraphs.create(brand!.slug, name, objective, source); setSelectedId(made.id) })} />}
      {dialog === 'template' && <TemplateModal slug={brand!.slug} templates={load.data.templates} sources={load.data.sources} close={() => setDialog(null)} done={(id) => { setSelectedId(id); refresh(); setDialog(null) }} />}
      {dialog === 'attach' && graph && <AttachModal close={() => setDialog(null)} submit={(body) => act('Asset attached to draft graph.', () => campaignGraphs.attach(graph.id, body))} />}
      {dialog === 'relationship' && graph && <RelationshipModal members={activeMembers} close={() => setDialog(null)} submit={(from, to, type, reason, notes) => act('Relationship added.', () => campaignGraphs.relate(graph.id, from, to, type, reason, notes))} />}
      {dialog === 'flight' && graph && <FlightModal close={() => setDialog(null)} submit={(name, start, end, reason) => act('Campaign flight added.', () => campaignGraphs.addFlight(graph.id, name, start, end, reason))} />}
      {dialog === 'metric' && metricMember && <MetricModal member={metricMember} close={() => { setDialog(null); setMetricMember(null) }} submit={(body) => act('Aggregate metric recorded.', () => campaignGraphs.metric(metricMember.id, body))} />}
    </>}
  </Shell>
}

async function reorder(graph: CampaignGraph, members: CampaignMembership[], from: number, to: number, act: (label: string, fn: () => Promise<unknown>) => Promise<void>) { const ids = members.map((m) => m.id); const [moving] = ids.splice(from, 1); ids.splice(to, 0, moving); await act('Touchpoints reordered.', () => campaignGraphs.reorder(graph.id, ids, 'Operator reordered the visible active campaign path.')) }

function Measurement({ graph, measurement, onMetric }: { graph: CampaignGraph; measurement?: Awaited<ReturnType<typeof campaignGraphs.measurement>>; onMetric: (member: CampaignMembership) => void }) {
  const observations = measurement ? Object.values(measurement.assets).flatMap((asset) => asset.observations) : []
  const totals = observations.reduce((sum, item) => ({ conversions: sum.conversions + item.conversions, revenue: sum.revenue + item.revenue_cents }), { conversions: 0, revenue: 0 })
  return <Card><CardHeader icon="chart" title="Measurement" sub="individual observations roll up safely; unlike channel metrics are not invented" right={<Chip kind={observations.length ? 'ok' : 'neutral'}>{observations.length} observations</Chip>} /><div className="grid card-b campaigns-three-col"><div><div className="meta">Conversions</div><b>{totals.conversions}</b></div><div><div className="meta">Revenue</div><b>{money(totals.revenue / 100)}</b></div><div><div className="meta">Measured assets</div><b>{Object.keys(measurement?.assets ?? {}).length}/{graph.memberships.filter((m) => Boolean(m.active)).length}</b></div></div>{observations.slice(-8).reverse().map((item) => <div key={item.id} className="card-b campaign-row"><div className="row"><b>{shortDateTime(item.observed_at)}</b><Chip kind="info">{item.attribution_confidence}</Chip></div><div className="meta">{Object.entries(item.native_metrics).map(([key, value]) => `${titleCase(key)} ${value}`).join(' · ')} · conversions {item.conversions}</div></div>)}{!observations.length && <div className="card-b"><button className="btn sm" disabled={!graph.primary_anchor} onClick={() => graph.primary_anchor && onMetric(graph.primary_anchor)}>Record first aggregate observation</button></div>}</Card>
}

function TrackedDestination({ packages, act }: { packages: { id: string; web?: { url?: string; tracked_url?: string } }[]; act: (label: string, fn: () => Promise<unknown>) => Promise<void> }) {
  const [url, setUrl] = useState('')
  if (!packages.length) return <Card><CardHeader icon="link" title="Tracked destination" /><Empty>This campaign has no newsletter distribution package. Tracked destinations are created on packages so draft X artifacts can be revised without approval or publishing.</Empty></Card>
  return <Card><CardHeader icon="link" title="Tracked destination" sub="creates tracked URLs and fresh draft revisions only" /><div className="card-b stack">{packages.map((item) => <div key={item.id} className="row"><span className="mono">{item.id}</span><span className="meta">{item.web?.tracked_url ?? item.web?.url ?? 'destination not bound'}</span></div>)}<form className="row" onSubmit={(event) => { event.preventDefault(); void act('Tracked destination bound; affected X items remain drafts.', () => campaignGraphs.bindDestination(packages[0].id, url)) }}><input aria-label="Destination URL" className="input" type="url" required value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://demo.example/guide" /><button className="btn" type="submit">Bind tracked destination</button></form></div></Card>
}

function CreateModal({ sources, close, submit }: { sources: Source[]; close: () => void; submit: (name: string, objective: string, source?: string) => void }) { const [name, setName] = useState(''), [objective, setObjective] = useState(''), [source, setSource] = useState(''); return <Modal title="Create draft campaign" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="campaign-create">Create draft</button></>}><form id="campaign-create" className="stack" onSubmit={(e) => { e.preventDefault(); submit(name, objective, source || undefined) }}><Field label="Campaign name" value={name} set={setName} /><Field label="Objective" value={objective} set={setObjective} /><Select label="Governed source (optional)" value={source} set={setSource} options={sources.map((s) => [s.id, s.title])} empty="No source" /><div className="ai-note"><Icon name="lock" size={15} />Creates a draft graph only. It cannot approve, schedule, or publish.</div></form></Modal> }

function AttachModal({ close, submit }: { close: () => void; submit: (body: Parameters<typeof campaignGraphs.attach>[1]) => void }) { const [assetType, setAssetType] = useState('web'), [assetId, setAssetId] = useState(''), [channel, setChannel] = useState('web'), [role, setRole] = useState('touchpoint'), [reason, setReason] = useState(''); return <Modal title="Attach campaign asset" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="attach">Attach</button></>}><form id="attach" className="stack" onSubmit={(e) => { e.preventDefault(); submit({ asset_type: assetType, asset_id: assetId, channel, role, reason, attribution_primary: role === 'anchor' }) }}><Field label="Asset type" value={assetType} set={setAssetType} /><Field label="Exact asset ID" value={assetId} set={setAssetId} /><Select label="Channel" value={channel} set={setChannel} options={['newsletter', 'email', 'web', 'youtube', 'x'].map((v) => [v, titleCase(v)])} /><Select label="Role" value={role} set={setRole} options={['anchor', 'touchpoint', 'supporting'].map((v) => [v, titleCase(v)])} /><Field label="Reason" value={reason} set={setReason} /></form></Modal> }

function RelationshipModal({ members, close, submit }: { members: CampaignMembership[]; close: () => void; submit: (from: string, to: string, type: string, reason: string, notes: string) => void }) { const [from, setFrom] = useState(members[0]?.id ?? ''), [to, setTo] = useState(members[1]?.id ?? ''), [type, setType] = useState('drives'), [reason, setReason] = useState(''), [notes, setNotes] = useState(''); const options = members.map((m) => [m.id, `${m.role}: ${m.asset_id}`]); return <Modal title="Declare reader path" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="relation" disabled={!from || !to || from === to}>Add relationship</button></>}><form id="relation" className="stack" onSubmit={(e) => { e.preventDefault(); submit(from, to, type, reason, notes) }}><Select label="From" value={from} set={setFrom} options={options} /><Select label="To" value={to} set={setTo} options={options} /><Field label="Relationship type" value={type} set={setType} /><Field label="Reason" value={reason} set={setReason} /><Field label="Notes (optional)" value={notes} set={setNotes} required={false} /></form></Modal> }

function FlightModal({ close, submit }: { close: () => void; submit: (name: string, start: string, end: string, reason: string) => void }) { const [name, setName] = useState('launch'), [start, setStart] = useState(''), [end, setEnd] = useState(''), [reason, setReason] = useState(''); return <Modal title="Add bounded flight" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="flight">Add flight</button></>}><form id="flight" className="stack" onSubmit={(e) => { e.preventDefault(); submit(name, new Date(start).toISOString(), new Date(end).toISOString(), reason) }}><Field label="Flight name" value={name} set={setName} /><Field label="Starts" value={start} set={setStart} type="datetime-local" /><Field label="Ends" value={end} set={setEnd} type="datetime-local" /><Field label="Reason" value={reason} set={setReason} /></form></Modal> }

function MetricModal({ member, close, submit }: { member: CampaignMembership; close: () => void; submit: (body: Parameters<typeof campaignGraphs.metric>[1]) => void }) { const [observed, setObserved] = useState(''), [key, setKey] = useState(''), [impressions, setImpressions] = useState(''), [clicks, setClicks] = useState(''), [conversions, setConversions] = useState('0'), [revenue, setRevenue] = useState('0'); return <Modal title={`Record aggregate evidence · ${member.asset_id}`} onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="metric">Record evidence</button></>}><form id="metric" className="stack" onSubmit={(e) => { e.preventDefault(); const native_metrics: Record<string, number> = {}; if (impressions) native_metrics[member.channel === 'newsletter' || member.channel === 'email' ? 'delivered' : member.channel === 'web' ? 'pageviews' : member.channel === 'youtube' ? 'views' : 'impressions'] = Number(impressions); if (clicks) native_metrics.clicks = Number(clicks); submit({ observed_at: new Date(observed).toISOString(), native_metrics, conversions: Number(conversions), revenue_cents: Math.round(Number(revenue) * 100), attribution_confidence: 'operator_reported_aggregate', idempotency_key: key }) }}><div className="ai-note"><Icon name="chart" size={15} />Enter aggregate totals only—never subscriber or visitor-level records.</div><Field label="Observed at" value={observed} set={setObserved} type="datetime-local" /><Field label="Evidence key (unique provider report ID)" value={key} set={setKey} /><Field label={member.channel === 'newsletter' || member.channel === 'email' ? 'Delivered' : member.channel === 'web' ? 'Pageviews' : member.channel === 'youtube' ? 'Views' : 'Impressions'} value={impressions} set={setImpressions} type="number" /><Field label="Clicks (optional)" value={clicks} set={setClicks} type="number" required={false} /><Field label="Conversions" value={conversions} set={setConversions} type="number" /><Field label="Revenue (USD)" value={revenue} set={setRevenue} type="number" /></form></Modal> }

function TemplateModal({ slug, templates, sources, close, done }: { slug: string; templates: CampaignTemplate[]; sources: Source[]; close: () => void; done: (id: string) => void }) { const [key, setKey] = useState(templates[0]?.template_key ?? ''), [source, setSource] = useState(sources[0]?.id ?? ''), [name, setName] = useState(''), [answers, setAnswers] = useState<Record<string, string>>({}), [ready, setReady] = useState(false), { notify } = useToast(); const template = templates.find((t) => t.template_key === key); const setAnswer = (id: string, value: string) => { setAnswers((current) => ({ ...current, [id]: value })); setReady(false) }; const preflight = async () => { try { await campaignGraphs.preflight(slug, key, answers); setReady(true); notify('Preflight passed. Nothing was created.') } catch (error) { notify(describe(error), 'bad') } }; const instantiate = async () => { try { const graph = await campaignGraphs.instantiate(slug, key, { answers, name, objective: answers.goal, source_id: source, idempotency_key: `ui:${key}:${source}:${name}` }); notify('Template instantiated as a draft graph.'); done(graph.id) } catch (error) { notify(describe(error), 'bad') } }; return <Modal title="Instantiate governed campaign template" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn" onClick={() => void preflight()}>Run read-only preflight</button><button className="btn primary" disabled={!ready || !name || !source} onClick={() => void instantiate()}>Create draft graph</button></>}><Select label="Template" value={key} set={(v) => { setKey(v); setReady(false) }} options={templates.map((t) => [t.template_key, t.name])} /><Field label="Campaign name" value={name} set={setName} /><Select label="Governed source" value={source} set={setSource} options={sources.map((s) => [s.id, s.title])} />{template?.contract.questions.map((q) => <Field key={q.id} label={q.label} value={answers[q.id] ?? ''} set={(v) => setAnswer(q.id, v)} required={q.required} />)}<div className="meta">Hard guardrails: {template?.contract.guardrails.hard.join(' · ')}</div></Modal> }

function Field({ label, value, set, type = 'text', required = true }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label className="field"><span>{label}</span><input className="input" type={type} required={required} min={type === 'number' ? 0 : undefined} value={value} onChange={(e) => set(e.target.value)} /></label> }
function Select({ label, value, set, options, empty }: { label: string; value: string; set: (value: string) => void; options: string[][]; empty?: string }) { return <label className="field"><span>{label}</span><select className="input" required={!empty} value={value} onChange={(e) => set(e.target.value)}>{empty && <option value="">{empty}</option>}{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label> }
