import { useState, type FormEvent } from 'react'
import { settings } from '../api/endpoints'
import type { BrandSettings } from '../api/types'
import { describe, useLoad } from '../api/useLoad'
import { Icon } from '../components/icons'
import { Shell } from '../components/Shell'
import { Card, CardHeader, Chip, Empty, ErrorState, Loading, Modal, StatusChip } from '../components/ui'
import { shortDateTime, titleCase } from '../lib/format'
import { useBrands } from '../state/BrandContext'
import { useToast } from '../state/Toast'

export default function Settings() {
  const { selected, active } = useBrands(), brand = selected ? active[0] : undefined
  const load = useLoad(() => brand ? settings.get(brand.slug) : Promise.resolve(null), [brand?.slug])
  const { notify } = useToast()
  const [modal, setModal] = useState<'rate' | null>(null), [busy, setBusy] = useState(false), [limit, setLimit] = useState('25')
  const mutate = async (fn: () => Promise<unknown>, message: string) => { setBusy(true); try { await fn(); notify(message); setModal(null); load.reload() } catch (error) { notify(describe(error), 'bad') } finally { setBusy(false) } }
  if (!selected) return <Shell title="Settings"><Card><Empty>Select one brand to change its governed settings.</Empty></Card></Shell>
  return <Shell title="Settings" crumb={brand?.name} right={<Chip kind="agent" icon="lock">brand-scoped · audited · no provider action</Chip>}>
    {load.error && <ErrorState message={load.error} retry={load.reload} />}{load.loading && !load.data && <Loading label="Loading brand settings…" />}
    {brand && load.data && <><BrandEditor key={load.data.brand.updated_at} data={load.data} busy={busy} save={(body) => mutate(() => settings.update(brand.slug, body), 'Brand settings saved and audited.')} />
      <div className="grid settings-grid"><Card><CardHeader icon="chart" title="Provider rate cards" sub="customer-supplied estimates, never bundled vendor prices" right={<button className="btn sm" onClick={() => setModal('rate')}><Icon name="plus" size={13} />Add rate</button>} />{!load.data.rate_cards.length ? <Empty>No customer rate cards configured.</Empty> : load.data.rate_cards.map((rate) => <div className="card-b source-row" key={rate.id}><div className="row source-heading"><b>{titleCase(rate.billable_category)}</b><Chip kind="neutral">{rate.provider}</Chip></div><div>{rate.unit_price} {rate.currency} / {rate.unit_name}</div><div className="meta">{rate.version} · effective {shortDateTime(rate.effective_at)} · configured by {rate.configured_by}</div></div>)}</Card>
      <Card><CardHeader icon="clock" title="Brand automation" sub="schedules and bounded decision queue only" /><div className="card-b ai-note"><Icon name="lock" size={14} /><div><b>A tick does not call a provider.</b><div>It evaluates this brand's due schedules and queues eligible read, planning, or assisted work. Approval and provider execution stay separate.</div></div></div><div className="row" style={{ justifyContent: 'space-between' }}><div><b>{load.data.orchestration.schedules.enabled} enabled</b><div className="meta">{load.data.orchestration.schedules.due} due · {load.data.orchestration.pending_decisions} pending decisions</div></div><div className="row"><label className="field settings-limit"><span>Decision limit</span><input aria-label="Decision limit" className="input" type="number" min="1" max="50" value={limit} onChange={(event) => setLimit(event.target.value)} /></label><button className="btn primary" disabled={busy} onClick={() => mutate(() => settings.tick(brand.slug, Math.max(1, Math.min(50, Number(limit)))), 'Brand-only orchestration tick completed.')}>Run bounded tick</button></div></div>{!load.data.schedules.length ? <Empty>No schedules discovered for this brand.</Empty> : load.data.schedules.map((schedule) => <div className="card-b source-row" key={schedule.schedule_key}><div className="row source-heading"><div><b>{schedule.name}</b><div className="meta">{titleCase(schedule.action_type)} · every {Math.round(schedule.interval_seconds / 60)} min</div></div><StatusChip status={schedule.enabled ? 'enabled' : 'disabled'} /></div><div className="source-detail"><span className="meta">Next decision {shortDateTime(schedule.next_run_at)}</span><button className={`btn sm ${schedule.enabled ? 'danger' : ''}`} disabled={busy} onClick={() => mutate(() => settings.setSchedule(brand.slug, schedule.schedule_key, !schedule.enabled), `Schedule ${schedule.enabled ? 'disabled' : 'enabled'}.`)}>{schedule.enabled ? 'Disable schedule' : 'Enable schedule'}</button></div></div>)}</Card></div>
      <Card><CardHeader icon="history" title="Settings audit" sub="authenticated actor, reason, and before/after values" />{!load.data.audit.length ? <Empty>No settings changes recorded.</Empty> : load.data.audit.slice().reverse().map((item) => <div className="card-b source-row" key={item.sequence}><div className="row source-heading"><b>{item.reason}</b><span className="meta">{shortDateTime(item.at)}</span></div><div className="meta">{item.actor} · change #{item.sequence}</div></div>)}</Card>
      {modal === 'rate' && <RateCard busy={busy} close={() => setModal(null)} submit={(body) => mutate(() => settings.addRateCard(brand.slug, body), 'Customer rate card added.')} />}
    </>}
  </Shell>
}

function BrandEditor({ data, busy, save }: { data: BrandSettings; busy: boolean; save: (body: { mission: string; voice: string; compliance_rules: string; approval_policy: 'human_approval_required' | 'standing_approval'; reason: string }) => void }) {
  const [mission, setMission] = useState(data.brand.mission), [voice, setVoice] = useState(data.brand.voice), [rules, setRules] = useState(data.brand.compliance_rules), [policy, setPolicy] = useState(data.brand.approval_policy), [reason, setReason] = useState('')
  return <Card><CardHeader icon="gear" title="Brand governance" sub="mission, voice, compliance, and approval policy" /><form className="stack card-b" onSubmit={(event) => { event.preventDefault(); save({ mission, voice, compliance_rules: rules, approval_policy: policy, reason }) }}><label className="field"><span>Mission</span><textarea className="input" required value={mission} onChange={(event) => setMission(event.target.value)} /></label><label className="field"><span>Voice</span><textarea className="input" required value={voice} onChange={(event) => setVoice(event.target.value)} /></label><label className="field"><span>Compliance rules</span><textarea className="input" required value={rules} onChange={(event) => setRules(event.target.value)} /></label><label className="field"><span>Approval policy</span><select className="input" value={policy} onChange={(event) => setPolicy(event.target.value as typeof policy)}><option value="human_approval_required">Human approval required</option><option value="standing_approval">Standing approval</option></select></label><label className="field"><span>Reason for this change</span><input className="input" required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label><div className="row" style={{ justifyContent: 'flex-end' }}><button className="btn primary" disabled={busy}>Save governed settings</button></div></form></Card>
}

function RateCard({ close, submit, busy }: { close: () => void; submit: (body: { version: string; operation: 'beehiiv_read' | 'beehiiv_draft' | 'x_owned_read' | 'x_general_read' | 'x_plain_post' | 'x_link_post'; unit_price: string; currency: string; effective_at: string }) => void; busy: boolean }) {
  const [version, setVersion] = useState('customer-current'), [operation, setOperation] = useState<'beehiiv_read' | 'beehiiv_draft' | 'x_owned_read' | 'x_general_read' | 'x_plain_post' | 'x_link_post'>('beehiiv_read'), [price, setPrice] = useState('0'), [currency, setCurrency] = useState('USD')
  return <Modal title="Add customer rate card" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="rate-card" disabled={busy}>Add rate</button></>}><form id="rate-card" className="stack" onSubmit={(event: FormEvent) => { event.preventDefault(); submit({ version, operation, unit_price: price, currency, effective_at: new Date().toISOString() }) }}><label className="field"><span>Provider operation</span><select className="input" value={operation} onChange={(event) => setOperation(event.target.value as typeof operation)}><option value="beehiiv_read">Beehiiv read</option><option value="beehiiv_draft">Beehiiv draft</option><option value="x_owned_read">X owned-account read</option><option value="x_general_read">X general read</option><option value="x_plain_post">X plain post</option><option value="x_link_post">X link post</option></select></label><label className="field"><span>Rate-card version</span><input className="input" required value={version} onChange={(event) => setVersion(event.target.value)} /></label><label className="field"><span>Unit price</span><input className="input" required type="number" min="0" step="0.000001" value={price} onChange={(event) => setPrice(event.target.value)} /></label><label className="field"><span>Currency</span><input className="input" required pattern="[A-Za-z]{3}" maxLength={3} value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} /></label><div className="ai-note"><Icon name="lock" size={14} />Use the price from this customer's provider plan. Saving a rate never contacts or buys anything from the provider.</div></form></Modal>
}
