import { useState, type FormEvent } from 'react'
import { brands as brandsApi, integrations, sourceInputs } from '../api/endpoints'
import type { Source, ThirdPartySource } from '../api/types'
import { describe, useLoad } from '../api/useLoad'
import { ChannelIcon, Icon } from '../components/icons'
import { Shell } from '../components/Shell'
import { Card, CardHeader, Chip, Empty, ErrorState, Loading, Modal, StatusChip } from '../components/ui'
import { relTime, shortDateTime } from '../lib/format'
import { safeHttpUrl } from '../lib/review'
import { useBrands } from '../state/BrandContext'
import { useToast } from '../state/Toast'

async function loadSources(slug: string) {
  const [context, thirdParty, connectors, health, canonical, beehiivPulls] = await Promise.all([
    brandsApi.context(slug), sourceInputs.thirdParty(slug), integrations.connectors(slug),
    integrations.health(slug), sourceInputs.canonical(slug), sourceInputs.beehiivPulls(slug),
  ])
  return { sources: context.sources, thirdParty, connectors, health, canonical, beehiivPulls }
}

export default function Sources() {
  const { selected, active } = useBrands(), brand = selected ? active[0] : undefined
  const load = useLoad(() => brand ? loadSources(brand.slug) : Promise.resolve(null), [brand?.slug])
  const { notify } = useToast()
  const [modal, setModal] = useState<'add' | 'manual' | 'control' | null>(null)
  const [control, setControl] = useState<ThirdPartySource | null>(null)
  const [busy, setBusy] = useState<string | null>(null)
  const act = async (key: string, fn: () => Promise<unknown>, message: string) => { setBusy(key); try { await fn(); notify(message); load.reload(); setModal(null) } catch (error) { notify(describe(error), 'bad') } finally { setBusy(null) } }
  if (!selected) return <Shell title="Sources"><Card><Empty>Select one brand to inspect or configure its source inputs.</Empty></Card></Shell>
  return <Shell title="Sources" crumb={brand?.name} right={<Chip kind="agent" icon="lock">read-only inputs · no subscriber data</Chip>}>
    {load.error && <ErrorState message={load.error} retry={load.reload} />}{load.loading && !load.data && <Loading label="Loading governed inputs…" />}
    {brand && load.data && <>
      <div className="sources-summary grid"><Summary label="Fresh source items" value={load.data.sources.length} note="title, summary, link, and lifecycle metadata" /><Summary label="Public feeds" value={load.data.thirdParty.filter((item) => item.enabled).length} note={`${load.data.thirdParty.length} configured`} /><Summary label="Beehiiv read pulls" value={load.data.beehiivPulls.filter((item) => item.status === 'completed').length} note="completed aggregate-only receipts" /></div>
      <div className="row" style={{ justifyContent: 'space-between' }}><div className="meta">Every input is brand-scoped. Feed onboarding stores configuration only and performs no immediate network fetch.</div><div className="row"><button className="btn" onClick={() => setModal('manual')}><Icon name="file" size={14} />Add canonical input</button><button className="btn primary" onClick={() => setModal('add')}><Icon name="plus" size={14} />Add public feed</button></div></div>
      <Card><CardHeader icon="rss" title="Third-party feeds" sub="public RSS/Atom title, summary, and link metadata only" />{!load.data.thirdParty.length ? <Empty>No public feeds configured.</Empty> : load.data.thirdParty.map((feed) => <div className="card-b source-row" key={feed.connector_account_id}><div className="row source-heading"><div><b>{feed.publisher_name}</b><div className="meta">{feed.feed_format.toUpperCase()} · every {Math.round(feed.polling_interval_seconds / 60)} min · <span className="mono">{feed.content_policy}</span></div></div><div className="row"><StatusChip status={feed.connector_status} /><Chip kind={feed.enabled ? 'ok' : 'neutral'}>{feed.enabled ? 'polling enabled' : 'disabled'}</Chip></div></div><div className="source-detail"><div>{safeHttpUrl(feed.feed_url) ? <a href={safeHttpUrl(feed.feed_url)!} target="_blank" rel="noreferrer">{feed.feed_url}</a> : feed.feed_url}<div className="meta">Next pull {feed.schedule?.next_run_at ? shortDateTime(feed.schedule.next_run_at) : 'not scheduled'} · {feed.running_sync_jobs} running</div>{feed.last_error && <div className="meta source-error">{feed.last_error}</div>}</div><div className="row"><button className="btn sm" disabled={busy === feed.connector_account_id} onClick={() => void act(feed.connector_account_id, () => integrations.checkHealth(brand.slug, feed.connector_account_id), 'Read-only feed health check queued.')}>Check health</button><button className={`btn sm ${feed.enabled ? 'danger' : ''}`} onClick={() => { setControl(feed); setModal('control') }}>{feed.enabled ? 'Disable' : 'Enable'}</button></div></div></div>)}</Card>
      <Card><CardHeader icon="mail" title="Beehiiv read-only lane" sub="private account access stays in the helper or least-privilege insights connector" />
        <div className="card-b ai-note"><Icon name="lock" size={16} /><div><b>No newsletter bodies or subscriber records belong here.</b><div>BrandMan accepts post metadata and aggregate delivered, open, click, unsubscribe, and subscription totals only. Drafting, scheduling, sending, and publishing are forbidden on this lane.</div></div></div>
        {load.data.connectors.filter((item) => item.connector_type === 'beehiiv' && (item.capabilities.includes('metrics.read') || String(item.configuration?.connection_role ?? '') === 'beehiiv_read')).map((account) => <div className="card-b source-row" key={account.id}><div className="row source-heading"><div className="row"><ChannelIcon channel="beehiiv" /><div><b>{account.display_name}</b><div className="meta mono">{account.account_key}</div></div></div><div className="row"><StatusChip status={account.status} /><button className="btn sm" disabled={!['connected', 'healthy', 'active'].includes(account.status) || busy === `pull:${account.id}`} onClick={() => void act(`pull:${account.id}`, () => sourceInputs.requestBeehiivPull(brand.slug, account.id, new Date().toISOString()), 'Read-only Beehiiv metadata and aggregate measurement pull requested.')}>Request metadata + metrics</button></div></div></div>)}
        {load.data.beehiivPulls.slice(0, 6).map((pull) => <div className="card-b source-row" key={pull.id}><div className="row source-heading"><div><b>Aggregate pull</b><div className="meta">Due {shortDateTime(pull.scheduled_for)} · <span className="mono">{pull.id}</span></div></div><StatusChip status={pull.status} /></div>{pull.status === 'completed' && <div className="meta">{pull.posts_received ?? 0} posts · {pull.post_measurements_received ?? 0} post measurements · campaigns {(pull.measured_campaign_ids ?? []).join(', ') || 'none attributed'}</div>}</div>)}
      </Card>
      <FreshItems sources={load.data.sources} canonical={load.data.canonical} busy={busy} revalidate={(source) => void act(`source:${source.id}`, () => sourceInputs.revalidate(brand.slug, source.id, `operator:${source.id}:${new Date().toISOString().slice(0, 10)}`), 'Canonical metadata revalidation queued. This is not a semantic fact-check.')} />
      {modal === 'add' && <AddFeed close={() => setModal(null)} submit={(body) => act('add', () => sourceInputs.onboard(brand.slug, body), 'Public feed configured. Its first bounded read will occur on schedule.')} busy={busy === 'add'} />}
      {modal === 'manual' && <AddCanonical close={() => setModal(null)} submit={(body) => act('manual', () => sourceInputs.create(brand.slug, body), 'Canonical input saved for editorial review.')} busy={busy === 'manual'} />}
      {modal === 'control' && control && <ControlFeed source={control} close={() => setModal(null)} submit={(reason) => act(control.connector_account_id, () => sourceInputs.setEnabled(control.connector_account_id, !control.enabled, reason), `Feed ${control.enabled ? 'disabled' : 'enabled'}.`)} />}
    </>}
  </Shell>
}

function Summary({ label, value, note }: { label: string; value: number; note: string }) { return <Card className="kpi"><div className="lbl">{label}</div><div className="val">{value}</div><div className="meta">{note}</div></Card> }

function FreshItems({ sources, canonical, busy, revalidate }: { sources: Source[]; canonical: { source_id: string; observed_at: string; status: string; semantic_fact_check: false }[]; busy: string | null; revalidate: (source: Source) => void }) { const latest = new Map(canonical.map((item) => [item.source_id, item])); return <Card><CardHeader icon="file" title="Fresh inputs" sub="canonical source metadata, not verified editorial claims" />{!sources.length ? <Empty>No source items ingested yet.</Empty> : <table><thead><tr><th>Source</th><th>Type</th><th>State</th><th>Canonical metadata</th><th /></tr></thead><tbody>{sources.slice(0, 50).map((source) => { const evidence = latest.get(source.id); return <tr key={source.id}><td><b>{source.title}</b><div className="meta">{source.body_summary || 'No summary'}</div></td><td><Chip kind="neutral">{source.source_type}</Chip></td><td><StatusChip status={source.lifecycle_state} /></td><td>{evidence ? <><Chip kind={evidence.status === 'healthy' ? 'ok' : 'neutral'}>{evidence.status}</Chip><div className="meta">{relTime(evidence.observed_at)} · not a fact-check</div></> : <span className="meta">not checked</span>}</td><td><button className="btn sm" disabled={!source.url || busy === `source:${source.id}`} onClick={() => revalidate(source)}>Revalidate public page</button></td></tr>})}</tbody></table>}</Card> }

function AddFeed({ close, submit, busy }: { close: () => void; submit: (body: { publisher_name: string; feed_url: string; homepage_url?: string; feed_format: 'auto' | 'rss' | 'atom'; polling_interval_seconds: number; reason: string }) => void; busy: boolean }) { const [publisher, setPublisher] = useState(''), [feed, setFeed] = useState(''), [home, setHome] = useState(''), [format, setFormat] = useState<'auto' | 'rss' | 'atom'>('auto'), [minutes, setMinutes] = useState('30'), [reason, setReason] = useState(''); return <Modal title="Add governed public feed" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="add-feed" disabled={busy}>Configure feed</button></>}><form id="add-feed" className="stack" onSubmit={(e: FormEvent) => { e.preventDefault(); submit({ publisher_name: publisher, feed_url: feed, ...(home ? { homepage_url: home } : {}), feed_format: format, polling_interval_seconds: Number(minutes) * 60, reason }) }}><Field label="Publisher name" value={publisher} set={setPublisher} /><Field label="Public HTTPS feed URL" value={feed} set={setFeed} type="url" /><Field label="Public homepage (optional)" value={home} set={setHome} type="url" required={false} /><label className="field"><span>Feed format</span><select className="input" value={format} onChange={(e) => setFormat(e.target.value as typeof format)}><option value="auto">Detect automatically</option><option value="rss">RSS</option><option value="atom">Atom</option></select></label><Field label="Polling interval (minutes, minimum 15)" value={minutes} set={setMinutes} type="number" /><Field label="Why this source is in scope" value={reason} set={setReason} /><div className="ai-note"><Icon name="lock" size={15} />This saves configuration only. It accepts no credentials, query strings, private hosts, or full scraped article bodies.</div></form></Modal> }
function ControlFeed({ source, close, submit }: { source: ThirdPartySource; close: () => void; submit: (reason: string) => void }) { const [reason, setReason] = useState(''); return <Modal title={`${source.enabled ? 'Disable' : 'Enable'} ${source.publisher_name}`} onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className={`btn ${source.enabled ? 'danger' : 'primary'}`} form="control-feed">{source.enabled ? 'Disable polling' : 'Enable polling'}</button></>}><form id="control-feed" className="stack" onSubmit={(e) => { e.preventDefault(); submit(reason) }}><div>{source.enabled ? 'Pending and retrying sync work will be cancelled. Existing source evidence remains in the audit trail.' : 'The bounded public metadata schedule will resume.'}</div><Field label="Reason" value={reason} set={setReason} /></form></Modal> }
function AddCanonical({ close, submit, busy }: { close: () => void; submit: (body: { title: string; source_type: 'manual'; body_summary: string; url?: string; lifecycle_state: 'draft' }) => void; busy: boolean }) { const [title, setTitle] = useState(''), [summary, setSummary] = useState(''), [url, setUrl] = useState(''); return <Modal title="Add canonical input" onClose={close} footer={<><button className="btn" onClick={close}>Cancel</button><button className="btn primary" form="add-canonical" disabled={busy}>Save input</button></>}><form id="add-canonical" className="stack" onSubmit={(e) => { e.preventDefault(); submit({ title, body_summary: summary, ...(url ? { url } : {}), source_type: 'manual', lifecycle_state: 'draft' }) }}><Field label="Title" value={title} set={setTitle} /><label className="field"><span>Summary or source note</span><textarea className="input" required value={summary} onChange={(e) => setSummary(e.target.value)} /></label><Field label="Canonical public URL (optional)" value={url} set={setUrl} type="url" required={false} /><div className="ai-note"><Icon name="lock" size={15} />This creates an editorial input, not a verified fact, campaign, approval, or provider action.</div></form></Modal> }
function Field({ label, value, set, type = 'text', required = true }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label className="field"><span>{label}</span><input className="input" type={type} required={required} min={type === 'number' ? 15 : undefined} value={value} onChange={(e) => set(e.target.value)} /></label> }
